version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: mongo
    ports:
      - 27017:27017